#import = [
#  "~/.config/alacritty/themes/themes/solarized_dark.toml",
#]

import =[
  "~/.config/alacritty/themes/themes/tokyo-night.html"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 16
padding.y = 14
decorations = "None"
opacity = 1.0

[font]
size = 12.0

[font.bold]
family = "Berkeley Mono"
style = "Bold"

[font.bold_italic]
family = "Berkeley Mono"
style = "Bold Italic"

[font.italic]
family = "Berkeley Mono"
style = "Italic"

[font.normal]
family = "Berkeley Mono"
style = "Regular"
